### ISSUE TITLE
nodeinfoにVRTL実装有無を追加し、リレー側の一覧で印を表示出来るようにする

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/misskey#20]
### Summary

> すっごい雑な思いつきなんですけど、 https://relay.virtualkemomimi.net/ の一覧にVRTL実装してるかどうかの印付けたりしても面白いかもしれない…なんて思ったり
https://misskey.niri.la/notes/9t5dd19kzy

Related: #19 

### Purpose

なんかあると嬉しそう(本当にそうでしょうか?)

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
(VRTL追加時には触れられていないけど)この辺りも関連?
(vrtlAvailableがデフォルトポリシーの内容に入ってなかったりなどもあったので忘れてるのかスルーしたのか不明)
https://github.com/anatawa12/misskey/blob/a2603986e93288579927aee75ea3a27799843afd/packages/backend/src/server/NodeinfoServerService.ts#L117

**Comment by anatawa12** [comment]
implemented
